### ISSUE TITLE
localization for UIAlertController possible?

### ISSUE THREAD

**Issue by TomMajor** [nickoneill/PermissionScope#104]
I am using localized strings like here:
https://github.com/nickoneill/PermissionScope/pull/12#issuecomment-96428580

Would it be possible to add this method also for the showDeniedAlert function? Otherwise the localization is somewhat broken, because of a mixed language if using this framework on a non-English system.

I would need these strings here:

"Permission for \(permission) was denied."
"Please enable access to \(permission) in the Settings app"
"OK"
"Show me"

Well, actually "OK" is fine without translation :)
Not sure how the method you already have (e.g. "Allow Camera" = "";) would work with this:
\(permission)
I could of course patch this for myself locally, but then with each update I would loose the patch.

Thanks,
Tom

**Comment by bre7** [comment]
Those strings were already localized by Leshich in #103 which I've just merged. ~~README needs an update about all the keys.~~

Keys updated in https://github.com/nickoneill/PermissionScope/pull/12#issuecomment-96428580

**Comment by TomMajor** [comment]
Hello bre7,

wow, that was fast, thank you very much.

I am new to CocoaPods, I did a "pod update", also a "pod update 
PermissionScope" in my project directory, but your/Leshich change from 
today does not show in my project.

Do I miss something here? Sorry if this is a silly question. Asking 
Google told me that pod update should be the right thing to do.

Thanks,
Tom

bre7 schrieb am 10.10.2015 um 23:51:

**Comment by bre7** [comment]
Nope, you just need to wait for @nickoneill to push the new version to CP. You could also add this to your podfile:

``` ruby
pod 'PermissionScope', :head
```

Using `:head` instead of a fixed version will always check out the master branch from the repo.

**Comment by TomMajor** [comment]
Thanks

bre7 schrieb am 11.10.2015 um 00:57:

**Comment by nickoneill** [comment]
Use `:head` if it's important for you today. I'm going to review and test the new contacts framework PR and push a new version out to cocoapods tomorrow or Monday.

**Comment by TomMajor** [comment]
Did a manual update. Localization is working great now, thank you.
