### ISSUE TITLE
why can't pull it to local from github 

### ISSUE THREAD

**Issue by onlyver** [nickoneill/PermissionScope#105]
`PermissionScope (~> 1.0)` required by `Podfile`

**Comment by nickoneill** [comment]
Sorry, you'll have to be more clear about the issue you're having here. Are you trying to get this from cocoapods or installing manually? I highly suggest the cocoapods installation instructions in the readme.

**Comment by onlyver** [comment]
OC is used through out all my project, and I haven't start use swift, I just follow your "README" , I can't found the reason ,can you give me some advice? thanks for your time to answer my question .

**Comment by nickoneill** [comment]
There's an example Objective-C project in the repo, it shows how to integrate and use PermissionScope in an ObjC context.

**Comment by bre7** [comment]
Paste your Podfile

**Comment by onlyver** [comment]
platform :ios,'7.0'
pod 'AFNetworking', '~> 2.6.0'
pod 'MJRefresh', '~> 1.4.1'
pod 'MagicalRecord', '~> 2.3.0'
pod 'GPUImage', '~> 0.1.7'
pod 'iRate', '~> 1.11.4'
pod 'PermissionScope', '~> 1.0'
pod 'SVProgressHUD', '~> 1.1.3'

this list  install fail ,and left the error "[!] Unable to satisfy the following requirements:
- `PermissionScope (~> 1.0)` required by `Podfile`"

**Comment by bre7** [comment]
As stated in the README, PermissionScope only supports iOS 8+. Your podfile has iOS7 set as the platform.
