### ISSUE TITLE
Option to turn CBPeripheralManagerOptionShowPowerAlertKey off

### ISSUE THREAD

**Issue by cgst** [nickoneill/PermissionScope#106]
PermissionScope triggers a system bluetooth power-on alert when checking for Bluetooth permissions. (CBPeripheralManagerOptionShowPowerAlertKey: true)

It would be great if there was on option to turn off this behavior.

**Comment by nickoneill** [comment]
Thanks! :+1: I'll check this out.

**Comment by nickoneill** [comment]
Disabling the alert is the right thing to do for pscope, we have enough other messaging around it.

**Comment by nickoneill** [comment]
Merged the fixes that default this to off. If we need an option for this, it can be handled with #113.
