### ISSUE TITLE
Notifications and actions

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#11]
Easy and fast ways to do it:
- Add an extra attribute to the PermissionConfig struct (AnyObject? :no_entry_sign: )
- PermissionConfig class instead of struct (each class also would implement a protocol [status and request functions]). LocationConfig would have an extra attribute called "category: {UIMutableUserNotificationCategory}"

**Comment by nickoneill** [comment]
I'm a bit confused by the suggestion here, a more clear plan for what problem this is fixing and how you plan do do it would be great.

I am hesitant to change PermissionConfig if it means more work for the implementing user. Again, I'm not entirely sure what's being suggested but we should just do the right thing for the 90% case if at all possible.

**Comment by bre7** [comment]
Problem: Unable to add categories for notifications ("Actionable/Interactive Push notifications")

Solutions: First comment. I'll try to think of a better way that doesn't include sub-classes

**Comment by nickoneill** [comment]
Ah, ok! We could simply have a category optional on PermissionConfig and, if you require a category on notifications, you can set that to something non-nil. And we'll just use it during the notification request. None of the other config types would use it.

I am not opposed to having the extra nil property on everything else for the sake of simplicity!

**Comment by bre7** [comment]
Cool, I'll add it later then

**Comment by nickoneill** [comment]
Looks good!
