### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by AdventuresOfMar** [nickoneill/PermissionScope#112]
Hello, I just pulled permissionscope into my project via cocoapods, I followed your instructions but permissions don't pop up for my iphone 6 only the emulator

**Comment by nickoneill** [comment]
Hey @AdventureOfMar, are you using this in an existing project? Keep in mind the dialog will only open if you have _unaccepted_ permissions; it's automatically bypassed if all the permissions are already granted.

**Comment by AdventuresOfMar** [comment]
Hi @nickoneill :) I am, first time building the app on my iphone 6 and the dialogs never appear. My xcode is xcode 7 with swift 2.1

**Comment by nickoneill** [comment]
I'm not sure what the issue is. We could potentially narrow it down if you post the relevant code that you're using for permissionscope.

**Comment by AdventureOfMar** [comment]
import Foundation
import UIKit
import Parse
import CoreAudio
import PermissionScope
import Parse

class loginViewController: UIViewController, UITextFieldDelegate {
  
    
    let pscope = PermissionScope()
    
    
    // This constraint ties an element at zero points from the bottom layout guide
    
    @IBOutlet weak var emailUsernameTextField: UITextField!
   
    @IBOutlet weak var passwordTextField: UITextField!
    
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var faitLogo: UIImageView!
    @IBOutlet weak var fbVerticalSpace: NSLayoutConstraint!

    @IBOutlet weak var contentContainerView: UIView!
    @IBOutlet weak var contentContainerVerticalSpace: NSLayoutConstraint!
    
   
    @IBOutlet weak var loginButton: UIButton!
    @IBOutlet weak var forgotPassword: UIButton!
    
    @IBOutlet weak var emailLabel: UILabel!
    @IBOutlet weak var emailLabelConstraint: NSLayoutConstraint!
    @IBOutlet weak var emailUnderline: grayLine!
    @IBOutlet weak var emailUnderlineConstraint: NSLayoutConstraint!
    
    @IBOutlet weak var passwordLabel: UILabel!
    @IBOutlet weak var passwordLabelConstraint: NSLayoutConstraint!
    @IBOutlet weak var passwordUnderline: grayLine!
    @IBOutlet weak var passwordUnderlineConstraint: NSLayoutConstraint!
    
    @IBOutlet weak var signUpConstraint: NSLayoutConstraint!
    
    var actInd: UIActivityIndicatorView = UIActivityIndicatorView(frame: CGRectMake(0,0,150,150)) as UIActivityIndicatorView
    var timesThroughAnimation = 0
    var ct = true
    var firstAnimation = true
    
    
    
    //var labelFont:UIFont             = .systemFontOfSize(14)
    //var  buttonFont:UIFont            = .boldSystemFontOfSize(14)
    
    override func viewDidLoad() {
        super.viewDidLoad()
         self.actInd.center = self.view.center
            self.actInd.hidesWhenStopped = true
        self.actInd.activityIndicatorViewStyle = UIActivityIndicatorViewStyle.Gray
        view.addSubview(self.actInd)
        loginButton.hidden = true
        emailUsernameTextField.delegate = self
        passwordTextField.delegate = self
       
        pscope.authorizedButtonColor = UIColor(red: 0.38, green: 0.56, blue: 0.68, alpha: 1)
        pscope.permissionButtonBorderColor  = UIColor(red: 0.38, green: 0.56, blue: 0.68, alpha: 1)
        pscope.permissionButtonTextColor = UIColor(red: 0.38, green: 0.56, blue: 0.68, alpha: 1)
        pscope.unauthorizedButtonColor = UIColor(red: 0.84, green: 0.46, blue: 0.46, alpha: 1)
        pscope.closeButtonTextColor = UIColor(red: 0.38, green: 0.56, blue: 0.68, alpha: 1)
         //public var labelFont:UIFont             = .systemFontOfSize(14)
        //pscope.labelFont.familyName = "helvetica"'
        //let font = UIFont(name: "opensans-regular-webfont", size: 14)
        //pscope.labelFont = font!
        //pscope.buttonFont = font!
        setupInput()
        keyboardGoAway()
        
        // Set up permissions
        pscope.addPermission(CameraPermission(),
            message: "Permission for your camera so you can take sweet pictures")
        pscope.addPermission(MicrophonePermission(),
            message: "Permission for your mic so you can record video/sound")
        pscope.addPermission(PhotosPermission(),
            message: "Permission for your photos so you can get previously taken pictures")
        
    }
    
    override func prefersStatusBarHidden() -> Bool {
        return true
    }
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    // an example of how to use the unified permissions API
    func checkContacts() {
        switch PermissionScope().statusContacts() {
        case .Unknown:
            // ask
            PermissionScope().requestContacts()
        case .Unauthorized, .Disabled:
            // bummer
            return
        case .Authorized:
            // thanks!
            return
        }
    }
    
    @IBAction func askPermissions(sender: AnyObject) {
        
        // Show dialog with callbacks
        //permission scope errors called here
        
        pscope.show({ (finished, results) -> Void in
            print("got results \(results)")
            }, cancelled: { (results) -> Void in
                print("thing was cancelled")
        })

    }
 
  
    
    //MARK: Check to see status of  textfield input then animate login button slide in slide out
    var timer: NSTimer? = nil
    
    func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
        
        timer?.invalidate()
        timer = NSTimer.scheduledTimerWithTimeInterval(0.2, target: self, selector: Selector("getHints:"), userInfo: textField, repeats: false)
       
        
        
        return true
    }
    
    func getHints(timer: NSTimer) {
        
        //println("Hints for textField: \(timer.userInfo!)")
        statusOfField()
        
    }
    

    func statusOfField(){
    
        
        
        if(isEmpty(emailUsernameTextField) && isEmpty(passwordTextField)){
            if(ct ==  true){
            
            self.loginButton.slideInFromLeft()
            self.loginButton.hidden = false
             ct = false
            }
        }
        
        else {
           
           self.view.layoutIfNeeded()
            UIView.animateWithDuration(0.5, animations: {
                self.loginButton.hidden = true
                self.view.layoutIfNeeded()
                
                })
            
            ct = true
        }
        
     
       
    }
            
    //MARK: Check If Empty
    
    func isEmpty(field: UITextField) -> Bool{
        
        let textField = field.text
        
        if (!textField!.isEmpty) {
        return true
        }
        else {
        return false
        }
        
    }

    
    
    
    func setupInput(){
        // Do any additional setup after loading the view, typically from a nib.
        emailUsernameTextField.attributedPlaceholder = NSAttributedString(string:"Email/Username", attributes:[NSForegroundColorAttributeName: UIColor(red: (123/255.0), green: (129/255.0), blue: (133/255.0), alpha: 1.0)])
        
        passwordTextField.attributedPlaceholder = NSAttributedString(string:"Password", attributes:[NSForegroundColorAttributeName:  UIColor(red: (123/255.0), green: (129/255.0), blue: (133/255.0), alpha: 1.0)])
    }
    
    
    
    //NARJ: Getting rid of keeyboards
    func keyboardGoAway(){
        
        let swipe: UISwipeGestureRecognizer = UISwipeGestureRecognizer(target: self, action: "dismissKeyboard")
        
        swipe.direction = UISwipeGestureRecognizerDirection.Down
        
        self.view.addGestureRecognizer(swipe)
        
        emailUsernameTextField.delegate = self
        passwordTextField.delegate = self
        
        let tapRec = UITapGestureRecognizer()
        tapRec.addTarget(self, action: "tappedView")
        contentContainerView.addGestureRecognizer(tapRec)
        contentContainerView.userInteractionEnabled = true
    }

    
    func tappedView(){
        self.view.endEditing(true)
        self.view.endEditing(true)
        self.view.layoutIfNeeded()
        UIView.animateWithDuration(0.5, animations: {
            self.contentContainerVerticalSpace.constant = 100
            self.signUpConstraint.constant = 15
            self.faitLogo.transform  = CGAffineTransformMakeScale(1.0, 1.0)
            self.fbVerticalSpace.constant = 50
            self.view.layoutIfNeeded()
            self.firstAnimation = true
        })
        

    }
    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
        UIApplication.sharedApplication().statusBarHidden = false
        
    }
    
   
    
    
    func dismissKeyboard(){
        self.view.endEditing(true)
        self.view.layoutIfNeeded()
        UIView.animateWithDuration(0.5, animations: {
            self.contentContainerVerticalSpace.constant = 100
            self.signUpConstraint.constant = 15
            self.faitLogo.transform  = CGAffineTransformMakeScale(1.0, 1.0)
             self.fbVerticalSpace.constant = 50
            self.view.layoutIfNeeded()
             self.firstAnimation = true
        })
        
        

    }

    
    func textFieldShouldReturn(textField: UITextField) -> Bool {
        
        if textField == self.emailUsernameTextField {
           
             self.passwordTextField.becomeFirstResponder()
        }
        
        switch textField {
        case self.emailUsernameTextField:
            self.passwordTextField.becomeFirstResponder()
            break
        case self.passwordTextField:
            self.resignFirstResponder()
            self.view.endEditing(true)
            self.view.layoutIfNeeded()
            UIView.animateWithDuration(0.5, animations: {
                self.contentContainerVerticalSpace.constant = 100
                self.signUpConstraint.constant = 15
                self.faitLogo.transform  = CGAffineTransformMakeScale(1.0, 1.0)
                self.fbVerticalSpace.constant = 50
                self.view.layoutIfNeeded()
                self.firstAnimation = true
            })

            break
            
        default:
            break
        }

        
        
        

        textField.resignFirstResponder()
        return true
    }
    
    
    func textFieldDidBeginEditing(textField: UITextField) {
        
      
        
        if(firstAnimation == true ){
            self.view.layoutIfNeeded()
            UIView.animateWithDuration(0.5, animations: {
                self.contentContainerVerticalSpace.constant = 2
                self.faitLogo.transform  = CGAffineTransformMakeScale(0.5, 0.5)
                self.fbVerticalSpace.constant = 16
                self.signUpConstraint.constant = 30
                self.view.layoutIfNeeded()
                
                }, completion: {
                    (value: Bool) in
                    self.firstAnimation = false
            })
            
           
        }
            
        
        
        
        if (textField == emailUsernameTextField){
          
        scrollView.setContentOffset(CGPointMake(0, 25), animated: true)
            
        }
        else{
            
        scrollView.setContentOffset(CGPointMake(0, 25), animated: true)
           
        
        }
       
        //println(timesThroughAnimation)
        
    }
    
    
    
    func textFieldDidEndEditing(textField: UITextField) {
        
        
        
            scrollView.setContentOffset(CGPointMake(0, 0), animated: true)
    }

    /*override func shouldPerformSegueWithIdentifier(identifier: String!, sender: AnyObject!) -> Bool {
    
        
    
    }*/

    
 

    //MARK: Actions

    @IBAction func loginAction(sender: AnyObject) {

        let username = self.emailUsernameTextField.text
        let password = self.passwordTextField.text
        _ = false
       
        
        
            self.actInd.startAnimating()
            
            PFUser.logInWithUsernameInBackground(username!, password: password!, block: {(user, error)  ->
            Void in
            
                self.actInd.stopAnimating()
                
                if((user) != nil){
                    
                    /*var alert = UIAlertView(title: "Succcess", message: "logged In", delegate: self, cancelButtonTitle: "OK")
                    alert.show()*/
                    self.performSegueWithIdentifier("login", sender: self)
                }
                else{
                    
                    
                    /* var alert = UIAlertView(title: "Error", message: "\(error!.localizedDescription)", delegate: self, cancelButtonTitle: "OK")
                    
                    alert.show()*/
                    
                    //var errorCode_e
                    
                    
                    
                    let userField = self.emailUsernameTextField
                    
                    let userLine = self.emailUnderline
                    
                    let passwordField = self.passwordTextField
                    
                    let passwordLine = self.passwordUnderline
                    
                    
                    
                    
                    
                    
                    
                    let animation = CABasicAnimation(keyPath: "position")
                    
                    animation.duration = 0.07
                    
                    animation.repeatCount = 4
                    
                    animation.autoreverses = true
                    
                    
                    
                    let part = [userField,userLine, passwordField,passwordLine]
                    
                    
                    
                    
                    
                    for items in part  {
                        
                        
                        
                        animation.fromValue = NSValue(CGPoint: CGPointMake(items.center.x - 10, items.center.y))
                        
                        animation.toValue = NSValue(CGPoint: CGPointMake(items.center.x + 10, items.center.y))
                        
                        items.layer.addAnimation(animation, forKey: "position")
                    }

                    
                }
                
                
            })
        
    }
  
    @IBAction func forgotPasswordAction(sender: AnyObject) {
        let username = self.emailUsernameTextField.text
        
        PFUser.requestPasswordResetForEmailInBackground(username!, block: { (succeeded: Bool, error: NSError?) -> Void in
            if error == nil {
                if succeeded { // SUCCESSFULLY SENT TO EMAIL
                    print("Reset email sent to your inbox");
                }
                else { // SOME PROBLEM OCCURED
                }
            }
            else { //ERROR OCCURED, DISPLAY ERROR MESSAGE
                print(error!.description);
            }
        });
    }
   
}

**Comment by AdventuresOfMar** [comment]
Here's my code: https://gist.github.com/bre7/d447e5e62a07e3c631d8

I think that I've been asking the wrong question. I completely looked over the `show.pscope` function and now getting the dialog to appear but, whenever I click the button to allow access to permissions or click on the `show me` button. I'm taken to the ios settings but the only thing that appears under allow access is cellular data
<img src="https://cloud.githubusercontent.com/assets/6402269/10917308/196ea6b2-822e-11e5-9792-981d629ab567.PNG" height="350"> <img src="https://cloud.githubusercontent.com/assets/6402269/10917305/1666c120-822e-11e5-9b0e-cb8db3493a2e.PNG" height="350"> <img src="https://cloud.githubusercontent.com/assets/6402269/10917301/11a9d1c2-822e-11e5-9754-6da93095c155.PNG" height="350"> <img src="https://cloud.githubusercontent.com/assets/6402269/10917295/0ea03660-822e-11e5-928a-283359c259d4.PNG" height="350">

**Comment by nickoneill** [comment]
Give this a shot without the debugger, i.e. run it on a device without Xcode. See #61 for a case where "show me" links don't work with the debugger.

**Comment by AdventuresOfMar** [comment]
Hmm, I'm not exactly sure that this is my issue. I've tried resetting my phone, deleting the app rebuilding, and running without the build strictly running on the device and still no luck. No matter what item I call to request permissions for i.e. contacts, location, photos, camera, microphone non of these items appear under Settings/AppName. The app name is correct but I'm not sure what I'm doing wrong.  I deleted the cocopod and reinstalled and still no luck either. When i download the zip from your repo everything works perfectly. A few errors that are being printed are as follows 

> 2015-11-03 16:17:31.463 Notice[2602:810922] _BSMachError: (os/kern) invalid capability (20)
> 2015-11-03 16:17:31.464 Notice[2602:810922] _BSMachError: (os/kern) invalid name (15)
> got results [Camera Unauthorized, Microphone Unknown, Photos Unknown]

**Comment by bre7** [comment]
Could you edit PermissionScope.swift [(Line 1140)](https://github.com/nickoneill/PermissionScope/blob/master/PermissionScope/PermissionScope.swift#L1140) and replace it with the following lines:
dispatch_after(0.2, dispatch_get_main_queue(), ^{
    UIApplication.sharedApplication().openURL(settingsUrl!)
});

**Comment by bre7** [comment]
From the Apple dev forums:

> Changing Localization native development region in info.plist to United States instead of en

Update: If everything works from the repo, there's no need for this issue anymore. Mentioned warnings/errors are the same as #127...Closing issue.
