### ISSUE TITLE
Add "Show me" button in disabled dialog

### ISSUE THREAD

**Issue by rlaferla** [nickoneill/PermissionScope#113]
Please change this dialog to say:  "Not Now" and "Settings":

![image](https://cloud.githubusercontent.com/assets/1135694/10893760/7cbf01a0-8178-11e5-99f4-999cbfc9af95.png)

Also is there a way to customize the text in this dialog?

**Comment by bre7** [comment]
PRs are welcome.

Check the readme, under _customization_, last paragraph for instructions on strings customization.

**Comment by nickoneill** [comment]
Hi @rlaferla, this particular message should only show when location services are disabled system-wide which is not a setting that will appear on the app-specific settings page (the only one we can link to in settings). Perhaps the text could be improved to indicate that location services are restricted system-wide?

We'd happily take a PR if you would like to improve the text in this case. Or you may simply override it in your own instance as per @bre7's instructions.

**Comment by rlaferla** [comment]
Understood.  However, adding a button that takes the user to the app-specific settings page is not a bad option.  Yes, it doesn't take them to the system setting but it does open up the Settings app, shows them that location is disabled and they are a couple of taps away to fixing it (if they so desire.)  The current behavior means that the user has to press the home button, find the settings app, launch it and find the privacy settings.

**Comment by bre7** [comment]
Bug: Use pretty description

**Comment by nickoneill** [comment]
All set here. Please give it a shot and see if you like it @rlaferla!

**Comment by rlaferla** [comment]
Nice!
