### ISSUE TITLE
Switch `onAuthChange` callback to return on the main thread

### ISSUE THREAD

**Issue by rlaferla** [nickoneill/PermissionScope#114]
Somehow the "show:" method is being executed in a background thread.

``` objc
    [permissionScope show:^(BOOL completed, NSArray *results) {
        NSLog(@"Changed: %@ - %@", @(completed), results);
        NSLog(@"[NSThread isMainThread] = %d", [NSThread isMainThread]);
   } cancelled:^(NSArray *x) {
        NSLog(@"cancelled");
   }];
```

which yields this error:

> "This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release."

**Comment by nickoneill** [comment]
Are you calling show from the main thread? If not, it's straghtforward to dispatch_async into main and call show from there.

**Comment by rlaferla** [comment]
Yes.  It is being called from the main thread.  I am using ObjC and am checking if the user gave permission for contacts, and if contacts are not authorized, show is called.  I verified that isMainThread = 1 before show is called and 0 when in the block.

**Comment by nickoneill** [comment]
It's difficult to know the source of this without more context for your code. This warning doesn't show up for everyone else so it's not completely obvious what you're doing differently.

What does your main thread check say if you move it before the call to show?

**Comment by rlaferla** [comment]
I just explained that.  It says that it's in the main thread BEFORE the call to "show" but not in the main thread in the block.

**Comment by rlaferla** [comment]
I think it's a bug in detectAndCallback() where the onAuthChange() is not being called on the main thread.

``` swift
    /**
    Rechecks the status of each requested permission, updates
    the PermisisonScope UI in response and calls your onAuthChange
    to notifiy the parent app.
    */
    func detectAndCallback() {
        // compile the results and pass them back if necessary
        if let onAuthChange = self.onAuthChange {
            self.getResultsForConfig({ results in
                self.allAuthorized({ areAuthorized in
                    onAuthChange(finished: areAuthorized, results: results)
                })
            })
        }

        dispatch_async(dispatch_get_main_queue()) {
            self.view.setNeedsLayout()

            // and hide if we've sucessfully got all permissions
            self.allAuthorized({ areAuthorized in
                if areAuthorized {
                    self.hide()
                }
            })
        }
    }
```

**Comment by rlaferla** [comment]
I tried submitting a fix but the CI server is complaining that there were no tests.  Please advise.  Also, do you agree with the fix and if so, can you submit it?

**Comment by nickoneill** [comment]
Thanks for the PR, I'll check it out.

I'm not real clear on which autolayout is happening on the background thread. The existing implementation has the setNeedsLayout() for permissionscope inside the dispatch_async block. Is this autolayout from your app that's happening on the background thread?

I'll be the first to admit that the ObjC support doesn't get the most care around here but I'd be really surprised if this was an issue only for ObjC implementations.

**Comment by rlaferla** [comment]
I don't think it's ObjC only.  I am using iOS 9.1 and that is using the Contacts API vs. the ABAddressBook api.  That could explain it but I haven't really looked.  In any case, I think it's good to ensure that callbacks are on the main thread.  In response to your other question, I was modifying the UI in the show block which is the onAuthChange() block.

**Comment by ky1ejs** [comment]
@nickoneill this is a similar change to my PR for the same problem a little while ago: #100

Looks good to me.

**Comment by bre7** [comment]
Mmmmh, the only issue I can see is related to CloudKit (not present in the master branch though), as status/request methods require network requests. I guess it doesn't really matter for now, there are far more important things that need to be finished before adding CK back.

**Comment by nickoneill** [comment]
If we're doing the `.Pending` status for cloudkit stuff (and I think that's our best option for async permission), this makes sense. We're always calling `onAuthChange` on the main thread, always immediately, and sometimes again once we've resolved an async permission.
