### ISSUE TITLE
Incorrect keys in .strings file

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#124]
Update https://github.com/nickoneill/PermissionScope/blob/master/files/English.strings
- Dialogs (denied/disabled) use pretty description instead of the permission's name
  - e.g: `"Permission for LocationAlways was denied." = "";` should be `"Permission for Location was denied." = "";`

**Comment by nickoneill** [comment]
Fixed in 9544e7405094791aa0fb09f06888e37c6d400e50
