### ISSUE TITLE
Add localisation files to project

### ISSUE THREAD

**Issue by yuraware** [nickoneill/PermissionScope#129]
We need localisation for this library. It would be great to have it localised inside library.
Please add localisation folders (`*.lproj`) with languages supported by iOS.

**Comment by bre7** [comment]
Hi @ykobets, PRs are welcome. As stated in the README:

> Please get in touch if you'd like to contribute a localization file for another language!

Localization is implemented using the keys located in `files/English.strings`. If you want to localize it to a specific language, clone it to your project and modify the content to your liking. (Keep in mind some keys are incorrect, as per #124)

Update: If someone wants to submit a new translation, we'll add the loc folders. Closing issue for now.
