### ISSUE TITLE
App Uploaded to TestFlight Doesn't Have Notification Settings...

### ISSUE THREAD

**Issue by jstheoriginal** [nickoneill/PermissionScope#137]
I uploaded a version of the app for internal testing and the notifications are gone and the popup only said "Denied" right off the bat. If I got to Settings there are no settings for notifications.

When I tested it from Xcode as a build it worked fine...I did have to add a Build Phase Run Script though to make it upload correctly on TestFlight as Apple rejected it at upload time due to the following errors: 

``` bash
ERROR ITMS-90087: "Unsupported Architectures. The executable for BB Links.app/Frameworks/PermissionScope.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'BB Links.app/Frameworks/PermissionScope.framework/PermissionScope' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
```

Once I added this build phase run script, it worked.

``` bash
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

Any ideas if this will be fixed in the next release?

**Comment by nickoneill** [comment]
Hey @jstheoriginal, I haven't seen this sort of behavior before. Where did you find the script to "fix" this issue?

Most ways you can fetch this repo are _not_ prebuilt, so the complaint about unsupported architectures may lay somewhere in your build process.

How did you download and integrate PermissionScope with your project?

**Comment by bre7** [comment]
It looks like he downloaded the ...framework.zip from the release

**Comment by nickoneill** [comment]
Yeah, that was my suspicion as well.

**Comment by jstheoriginal** [comment]
I used Carthage...so it is a .framework file. I wanted it to be simple to upgrade which is why i chose that route.  I guess I should just fork it and implement it that way instead?

**Comment by nickoneill** [comment]
Yes @jstheoriginal, but it should be building the framework from xcode, not just using a prebuilt framework it finds. I was under the impression that the framework zip for releases would only be used for test running by Carthage (and those archs should be fine for test running). Perhaps that has changed and Carthage is pulling the zipped framework for building now?

@kylejm You seem to be our resident Carthage expert. Do you know if this is normal behavior for Carthage?

**Comment by jstheoriginal** [comment]
this is what it shows in my Carthage folder:

https://www.dropbox.com/s/uka1vaghhlfi7vw/Screenshot%202015-12-10%2012.35.25.png?dl=0

**Comment by jstheoriginal** [comment]
And thanks @nickoneill I just did the non-framework way and got it to build fine so i'll submit that version in my next test flight build.

**Comment by jstheoriginal** [comment]
(I ran a checkout for Carthage instead of build)

**Comment by nickoneill** [comment]
Great to hear @jstheoriginal, I'll keep this issue open until I can figure out how to prevent this from happening to other carthage users.

**Comment by jstheoriginal** [comment]
Maybe the issue was that I added it via Carthage when I was using a beta build of Xcode?

**Comment by jstheoriginal** [comment]
Some strange stuff happening still. I uploaded a new build to TestFlight and the new one still says DENIED NOTIFICATIONS with no Notification options in Settings, BUT the same build on the simulator is fine.  See two pics of same instance.  What could be the issue?

<img src="https://cloud.githubusercontent.com/assets/5117473/11736119/ea3d19b2-9f8f-11e5-8c4f-3844fe72034e.png" height="300"> <img src="https://cloud.githubusercontent.com/assets/5117473/11736130/176eacc0-9f90-11e5-9b89-00b0c2fcbfa2.PNG" height="300">

**Comment by bre7** [comment]
Similar to #69 ? Should've been fixed.

**Comment by jstheoriginal** [comment]
So pretty sure I'm a complete n00b and didn't know I needed to use a production push notification certificate for TestFlight builds :-1: so i believe that's what the issue is! We'll see.

**Comment by ky1ejs** [comment]
@nickoneill that's not the case with Carthage, it will always download the `.zip` attached to a release if it can. To stop this behaviour, use the `--no-use-binaries` option :blush:.

Hope you've found the fix @jstheoriginal :pray:.

**Comment by jstheoriginal** [comment]
I'm still having issues with this...

the first time i load the app it looks like the first screen of the two i posted above. If i click Allow Notifications, it doesn't present the actual iOS pop-up but the pscope pop-up goes away. If i then go to settings, it shows notifications are enabled. But then if i close the app and go in again, it pops up again with the second screen above and there are no notification settings in the Settings screen anymore. Any idea what might cause this to happen?

**Comment by bre7** [comment]
Try again, but first reset the simulator. I'm not sure how can a permission be enabled/disabled in settings without using the iOS system alert.

**Comment by jstheoriginal** [comment]
I think these issues may be linked to the fact that I'm also using iCloud sync...so It's syncing my notification settings for the app and then screwing it up/making conflicts?

**Comment by bre7** [comment]
Try disabling it and testing Notifications without it

**Comment by nickoneill** [comment]
> so It's syncing my notification settings for the app

Is that really a thing that happens? It does make some sense that it's related to iCloud, this is similar behavior that we see when incorrectly dealing with async permissions.

**Comment by jstheoriginal** [comment]
yup...confirmed that that was the issue. it was syncing ALL iCloud NSUserDefaults instead of just select keys for my app. Bad bad bad. I've got it fixed now, so I think this can be closed.
