### ISSUE TITLE
Assertion Failed: Permission for Notifications already set.

### ISSUE THREAD

**Issue by jstheoriginal** [nickoneill/PermissionScope#139]
I am getting this error that causes my app to crash: assertion failed: Permission for Notifications already set: file /Users/Justin/Dropbox/Programming/iOS/MyApps/BBLinks/BBLinks/Helpers/PermissionScope/PermissionScope.swift, line 301

line 301 is:

``` swift
assert(configuredPermissions.first { $0.type == permission.type }.isNil, "Permission for \(permission.type) already set")
```

It's happening if I've already gotten permission, but for some reason the app is trying to call it again. Is there a way to prevent this? TIA.

**Comment by bre7** [comment]
Is the code that adds the permission in viewDidAppear by any chance ?

**Comment by jstheoriginal** [comment]
I called my "askForPermissionScope" function from the completion block of a delegate, but on an asynchronous thread.  That might be it? I've moved it back on to the main thread to see if that fixes issues.

**Comment by bre7** [comment]
Paste the code that calls `addPermission` if u can

**Comment by jstheoriginal** [comment]
Originally I had:

``` swift
func accountDetailViewController(controller: AccountDetailViewController, didFinishAddingAccount account: Account) {

        dataModel.addAccount(account)

        dismissViewControllerAnimated(true, completion: {
            dispatch_async(dispatch_get_main_queue()) {
                 self.askForNotificationPermission()
            }
        })
    }
```

Here's how I have it now to see if it fixes it (so far so good).

``` swift
func accountDetailViewController(controller: AccountDetailViewController, didFinishAddingAccount account: Account) {

        dataModel.addAccount(account)

        dismissViewControllerAnimated(true, completion: {
            self.askForNotificationPermission()
        })
    }
```

and this is the askForNotificationPermission function:

``` swift
func askForNotificationPermission() {
        // Set up permissions for notifications
        pscope.addPermission(NotificationsPermission(notificationCategories: nil),
            message: "Have every product link ready\r\nfor each new release!")
        pscope.closeButtonTextColor = UIColor.redColor()
        pscope.headerLabel.text = "Hey, Coach 💪!"
        pscope.bodyLabel.text = "Want to know when new\r\nproducts are added?"

        // Show dialog with callbacks
        pscope.show( {
            finished, results -> Void in // authorized
            UIApplication.sharedApplication().registerForRemoteNotifications()
            print("got results \(results)")
            },
            cancelled: { (results) -> Void in
                print("notifications dialog was cancelled")
        })
    }
```

**Comment by nickoneill** [comment]
@jstheoriginal Set your options for pscope once (addPermission, closeButtonTextColor, etc) in viewDidLoad. Then `.show` when you want to present.

**Comment by jstheoriginal** [comment]
Ah that makes sense! Will do.

**Comment by bre7** [comment]
Closing the issue. If the problem persists, reopen.

**Comment by jstheoriginal** [comment]
I've had this crash happen again after making the change @nickoneill suggested.

``` swift
assertion failed: Permission for Notifications already set: file /Users/Justin/Dropbox/Programming/iOS/MyApps/BBLinks/BBLinks/Helpers/PermissionScope/PermissionScope.swift, line 301
```

this happened after 

``` swift
got results [Notifications Authorized]
got results [Notifications Authorized]
```

displayed.

**Comment by bre7** [comment]
Seems to be the same issue. You can't add the same permission twice.

**Comment by jstheoriginal** [comment]
it’s really strange…i only add the notification in viewdidload.  but i’ve tried to reproduce the crash and it doesn’t happen again. it must be some sort of edge case…
