### ISSUE TITLE
Layout Issue

### ISSUE THREAD

**Issue by mythodeia** [nickoneill/PermissionScope#14]
Hello and thanks for sharing this library.
There is an issue with the layout of the presented view.
To replicate just to do this.
- open the app for the 1st time.
- tap to open the popup.
- tap outside of the popup to close it without pressing any of the buttons.
- tap to open the popup again. all items are shown in the top left corner.

screenshot attached below:
<img src="https://cloud.githubusercontent.com/assets/1748458/7408204/3a04902e-ef23-11e4-8322-a8bbb2fb4bb3.png" height="250">

**Comment by nickoneill** [comment]
Thanks for the report! I'll check this out today.

**Comment by mythodeia** [comment]
@nickoneill did you have a chance to look at it?

**Comment by nickoneill** [comment]
Fixed this in 8a800f3, sorry for the wait!

**Comment by mythodeia** [comment]
thanks for the support :+1:
