### ISSUE TITLE
How to use this awesome library in objective c?

### ISSUE THREAD

**Issue by afiq90** [nickoneill/PermissionScope#142]
Hey guys, I'm wondering How to use this awesome library in objective c? thank you in advance

**Comment by afiq90** [comment]
I figured it out by watching this video https://www.youtube.com/watch?v=OvDk5zXCFe8. thank you for great library.

**Comment by nickoneill** [comment]
Hey @afiq90, glad you figured it out. Let us know if you have any other questions.
