### ISSUE TITLE
Embedded Binaries signing problem

### ISSUE THREAD

**Issue by ghost** [nickoneill/PermissionScope#143]
I added the framework as a embedded binary.. But when i make archive the framework does not signing via my provisioning profile. What is the problem ?

![error1](https://cloud.githubusercontent.com/assets/12956798/12115937/b6586622-b3be-11e5-90e1-e9b49272dd11.png)

![error2 copy](https://cloud.githubusercontent.com/assets/12956798/12115967/eb45a822-b3be-11e5-88e0-adb01735b0e7.png)

**Comment by nickoneill** [comment]
Hey @testudorithm, in your project under Targets > Build Phases, is PermissionScope marked as a dependency?

**Comment by ghost** [comment]
no i add to project like this,

![screen shot 2016-01-05 at 19 17 22](https://cloud.githubusercontent.com/assets/12956798/12121972/08b85554-b3e1-11e5-9fa8-651c6308e652.png)

**Comment by nickoneill** [comment]
Is this a manual integration as opposed to cocoapods or carthage?

You should add PermissionScope to the dependency list as well if it's manual.

**Comment by ghost** [comment]
i get the framework in example project, and i add to embedded binaries also add Build Phases>Copy Files

**Comment by nickoneill** [comment]
I would _highly_ encourage you to use one of the other integration options because they do the hard work for you.

If you must integrate manually like you're doing now, add the project as a dependency in your Build Phases, and make sure 'Code Sign on Copy' is checked in your Copy Files phase.

**Comment by ghost** [comment]
![screen shot 2016-01-05 at 19 33 12](https://cloud.githubusercontent.com/assets/12956798/12122397/5d601f68-b3e3-11e5-8ae6-8a3927d4b0f5.png)

![rerr2](https://cloud.githubusercontent.com/assets/12956798/12122422/8f7a9442-b3e3-11e5-89ae-181659cc9835.png)

When i try adding as a dependency, i does not see the framework in selection

**Comment by nickoneill** [comment]
Oh, you just grab the framework rather than the project.

Instead of using the framework, drag the permissionscope project file into your project and take the same steps. This'll build the framework and include it for you.

**Comment by ghost** [comment]
Okay thanks :-)
