### ISSUE TITLE
1.0.2 Release

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#146]
The long awaited release comes. Please check it out with your respective projects and let me know if anything is wonky.

https://github.com/nickoneill/PermissionScope/releases/tag/1.0.2-beta

@bre7 @kylejm @evermeer @winkelsdorf @blender @felix-dumit @rlaferla

**Comment by ky1ejs** [comment]
HHELLLLL YYEAAAAHHHHH!

![giphy-6](https://cloud.githubusercontent.com/assets/3501212/12336832/778eedb6-bafe-11e5-819f-2ba9acfe3948.gif)

**Comment by felix-dumit** [comment]
I have made some minor changes to my branch in order to get it to work with my app, mainly related to bluetooth, I'll push a PR so you can take a look and see if it's in the scope of this release
Edit: #147

**Comment by nickoneill** [comment]
All set with this release! @felix-dumit, we'll tackle this for the next one.
