### ISSUE TITLE
Results always return as Unauthorized

### ISSUE THREAD

**Issue by AdventuresOfMar** [nickoneill/PermissionScope#150]
Hello I hope all is well,

I'm not quite sure how to explain my current issue but here's my attempt; bare with me: Currently I followed the steps adding permissionScope into my cocoapod file then followed the suggested steps on setting up permission scope. My issue is that once the permission scope pop up occurs if I click "Allow ____"  my button automatically turns orange and reads"Denied Camera". In results I get _____ Unauthorized even if I click the allow permission to ask for permission for the first time. I'm not sure what I'm doing wrong but thanks for taking the time to read through this issue

Code: https://gist.github.com/anonymous/6c4f4864f100ffcb1881

**Comment by AdventuresOfMar** [comment]
Not sure what was happening but simply deleted and reinstalled pod, works perfectly thank you

**Comment by nickoneill** [comment]
Thanks for the followup @AdventuresOfMar, glad it's working for you.
