### ISSUE TITLE
Crash on location permission 

### ISSUE THREAD

**Issue by cloudjanak** [nickoneill/PermissionScope#153]
![screen shot 2016-02-15 at 1 07 15 pm](https://cloud.githubusercontent.com/assets/7457258/13056731/28c3b9c8-d3e5-11e5-9fb1-ac1bfa387769.png)

**Comment by nickoneill** [comment]
From the readme:

> You must set these Info.plist keys for location to work
> 
> Use NSLocationAlwaysUsageDescription or NSLocationWhenInUseUsageDescription where appropriate for your app usage. You can specify which of these location permissions you wish to request with .LocationAlways or .LocationInUse while configuring PermissionScope.

**Comment by bre7** [comment]
As the assert message says, you need to set up the proper keys.
