### ISSUE TITLE
How to use localization file?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [nickoneill/PermissionScope#155]
Hello, I installed PermissionScope with Pods. the .strings files are not included. where should I place German.strings file if I want it to localize it to German?

**Comment by bre7** [comment]
You need to download it and add it to your project. Eg: http://www.raywenderlich.com/64401/internationalization-tutorial-for-ios-2014

**Comment by jimmyzzzzzzz** [comment]
Hi, thanks for the link explaining how localizable strings work.  However, my project has a different structure, I tried to follow the tutorial but it doesn't apply to my project.
I have 2 projects in my workspace, one is Pods and the other is my own project. Should I put Localizable string it in Pods/PermissionScope or my own project?

**Comment by bre7** [comment]
Your own

Edit: Closing issue for now
