### ISSUE TITLE
Upload a new release built with Swift 2.2 for Carthage

### ISSUE THREAD

**Issue by chrismanderson** [nickoneill/PermissionScope#158]
Getting the `Module file was created by an older version of the compiler error` when building PermissionScope via Carthage.

Seems to be a similar issue to https://github.com/nickoneill/PermissionScope/issues/110.

I was still able to build with the `--no-use-binaries` flag in Carthage.

**Comment by bre7** [comment]
Yeah, the archive uploaded was built using swift 2.1 and there's a note in the readme about it.

**Comment by nickoneill** [comment]
Thanks @chrismanderson, please use `--no-use-binaries` for now and we'll upload a new binary (or not! this process is getting frustrating) with the next release.

**Comment by bre7** [comment]
> Travis CI can automatically upload assets to your git tags on your GitHub repository.

Carthage auto-archive ?

Edit: More info here [https://github.com/facebook/ios-snapshot-test-case/issues/81](https://github.com/facebook/ios-snapshot-test-case/issues/81) and [Use travis-ci to upload your tagged prebuild frameworks](https://github.com/Carthage/Carthage#use-travis-ci-to-upload-your-tagged-prebuild-frameworks)

**Comment by chrismanderson** [comment]
Keeping up with Xcode releases is frustrating? That's totally the first time anyone has ever said that. :grinning: 

Thanks for that information, appreciate it.

**Comment by nickoneill** [comment]
@chrismanderson No, just reuploading new binaries for Carthage when nothing has changed. Makes me rethink the benefits from having uploaded binaries in the first place.

@bre7 We'd then be dependent on Travis to support new Xcode releases. I wonder if we can just rebuild with Xcode 7.3 and add to the old release?

**Comment by bre7** [comment]
Yes, you can add a new archive to an old release

**Comment by nickoneill** [comment]
OK, will give that a shot later today.

**Comment by bre7** [comment]
Archive uploaded. Warnings will be fixed in next version (pr #159)

**Comment by nickoneill** [comment]
Thanks for uploading this @bre7! It's weird that I can't find a record of a changed release binary anywhere in github, right?

**Comment by bre7** [comment]
True, there's no "uploaded date" in the release panel though it's part of the api https://api.github.com/repos/nickoneill/PermissionScope/releases/2512203.

BTW, it's easier to use this tool to upload files to releases: https://github.com/aktau/github-release
