### ISSUE TITLE
iPad Split View Bug

### ISSUE THREAD

**Issue by winkelsdorf** [nickoneill/PermissionScope#163]
Hi Nick,

just stumbled upon this nifty bug with the Demo playing with iPad Split View:
<img width="1136" alt="screenshot 2016-04-04 12 03 35" src="https://cloud.githubusercontent.com/assets/1413291/14245431/8cac342c-fa61-11e5-9211-e922144e02ae.png">
<img width="1136" alt="screenshot 2016-04-04 12 03 51" src="https://cloud.githubusercontent.com/assets/1413291/14245430/8caa3ee2-fa61-11e5-9e05-a5ee399aaaac.png">

Notice that the 1st screenshot is actually a Split View, not Overlay. It should be centered like the underlying View.

Source from :head as of today.

Looks like should be fixable with adjusting `viewWillLaoutSubviews()` usage of `UIScreen.mainScreen().bounds.size`.

Usually I would do this implementing traitCollectionDidChange: but the views are created by code.

Edit: Not that easy to fix. We could use `UIScreen.mainScreen().applicationFrame` instead, but it
1) is deprecated with iOS9
2) leaves a gap at the bottom (height of the statusbar is not part of applicationFrame)
3) and has issues with the close button.

Cheers,
Frederik

**Comment by nickoneill** [comment]
Thanks for this! We're going to swap this to a proper modal presentation at some point in time (#148) and it might be entirely resolved by that. If not, we'll tackle afterwards.

**Comment by winkelsdorf** [comment]
You're welcome! Ah yes, forgot about that.. Reference to this is kept in #148, closing this for now.
