### ISSUE TITLE
[bug]UI-less permission

### ISSUE THREAD

**Issue by quocan2812** [nickoneill/PermissionScope#165]
When I click UI-Less Permission, and choose not allow, and I click it again, nothing show me how to open setting, and the log:<UIAlertController: 0x7f9bcbd7f4d0> on <PermissionScope.PermissionScope: 0x7f9bcc061600> whose view is not in the window hierarchy!
Expected show me alert and help me open my setting.

**Comment by bre7** [comment]
Same as #130 ?

**Comment by nickoneill** [comment]
This is related... but I'm not sure it's a feature that we want. Let me get this straight, @quocan2812, you want to use UI-less methods for requesting the permission but then you want the alert UI if it's disabled?

I think you've got to go in one direction or another here. Either you use the PermissionScope UI and get all the features, or you use the UI-less requests and write your own UI. It would be pretty easy to pull the alert code with the Setttings link out of the permissionscope code for your own use.

**Comment by quocan2812** [comment]
thanks for reply,
yes I wrote code for my UI show alert when user not allow or disable this, and move it to setting, I open issue because I want to make your lib more comfortable, Thanks for all ^^
