### ISSUE TITLE
Transitive Dependency issue caused by pod install

### ISSUE THREAD

**Issue by BallerChan** [nickoneill/PermissionScope#169]
I am trying to use this cool pod; however, I am unable to even integrate it into my project with the installation instructions. The use_frameworks! line is deleting a bunch of other pods and creating transitive dependency issue. I have the platform set to 8.0. 

Executing pod install in terminal gives me the following error:

> [!] The 'Pods' target has transitive dependencies that include static binaries: (~/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a and ~/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a)

This causes the entire app to be unusable since many of the project files require these dependencies. 

Podfile:

``` ruby
platform :ios, '8.0'

xcodeproj 'ProjectName.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'


pod "SRMonthPicker"

pod 'SHSPhoneComponent', '~> 2.11'
pod 'iCarousel', '~> 1.7.6'
pod 'SHSPhoneComponent', '~> 2.11'
pod 'iCarousel', '~> 1.7.6'
pod 'M13BadgeView', '~> 1.0'
pod 'DateTools', '1.4.1'
pod 'TPKeyboardAvoiding', '~> 1.2'
pod "TSMessages", '0.9.10'
pod 'libPhoneNumber-iOS'
pod 'uservoice-iphone-sdk'
pod 'AWSiOSSDKv2', '~> 2.2'
pod 'Harpy', :git => 'https://github.com/boballer/Harpy'
pod 'Branch'
pod 'FBSDKCoreKit', '~> 4.7'
pod 'FBSDKLoginKit', '~> 4.7'
pod 'Analytics/Segmentio'
pod 'Analytics/Mixpanel'
pod 'Analytics/GoogleAnalytics'
pod 'OneSignal'
pod 'Intercom'
pod 'FLAnimatedImage', '~> 1.0'

pod 'PermissionScope'
use_frameworks!
```

**Comment by bre7** [comment]
That's related to Google Analytics & CocoaPods. I'm pretty sure they fixed that problem some time ago. Check stackoverflow. Just in case, be sure you have the latest version of CocoaPods.

Closing the issue for now.
