### ISSUE TITLE
I don't want it to show again if user denies

### ISSUE THREAD

**Issue by ingeniousgenius** [nickoneill/PermissionScope#173]
How can I do this cause it may start to become annyoing if it keeps on popping up.

**Comment by ingeniousgenius** [comment]
I figured it out never mind

**Comment by aliess** [comment]
can you please show how did you solve this ?

**Comment by nickoneill** [comment]
Hi @aliess, if you don't want the denied re-show behavior, simply check for the status of each of your permissions before you call `show()` and don't call it if any of them are the denied status.
