### ISSUE TITLE
How to use Permissions API in Objective-C?

### ISSUE THREAD

**Issue by thomasgpeng** [nickoneill/PermissionScope#175]
Does anyone know how to use the unified permissions API in an Objective-C project?  So far I've got:

```
PermissionScope *pScope = [[PermissionScope alloc] init];
if (pScope.statusLocationAlways == ???) {

}
```

I'm not sure how to use the Swift enums in this code however and couldn't find any examples.  Any help would be much appreciated.

**Comment by nickoneill** [comment]
Hi @thomasgpeng, have you examined the ObjC example project?

**Comment by thomasgpeng** [comment]
@nickoneill Yes I have, but it only has an example of how to use the UI (which works great), not the permissions API as far as I can tell.

Thanks a lot for this library, btw.  Rejected permisisons are a huge issue for my app so I'm looking forward to implementing this.

**Comment by bre7** [comment]
Check:
- https://github.com/nickoneill/PermissionScope#unified-permissions-api
- https://github.com/nickoneill/PermissionScope#calling-request-methods-directly

Mind the bugs (e.g: #130)
