### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by afiq90** [nickoneill/PermissionScope#176]
Does anyone know how to fix this error when using Xcode 8 BETA? Below is the error screenshot.

http://i.imgur.com/ImuQIUE.png

Any help will be much appreciated.

**Comment by nickoneill** [comment]
You can try the code in issue #174 to get the Swift 3 syntax in the short term. We'll have an official swift 3 branch soonish.

**Comment by SaifAlDilaimi** [comment]
any progress?

**Comment by bre7** [comment]
Check #174 which has the latest swift 3 changes

**Comment by bre7** [comment]
Check `swift3` branch (compatible with Xcode 8 beta 6)

TODO:
- Replace `UIControlState()` with `.normal`
- Recheck access control (open vs public). Class shouldn't be open (sub-classing makes no sense)

**Comment by nickoneill** [comment]
Just fixed both of these on the `swift3` branch, as well as some other issues.

Let me know if this makes sense for a swapover:
- push latest changes in `master` to `swift2` again
- tag a new 1.0.3 release/podspec for swift 2 in that branch
- rebase `swift3` on those changes
- merge `swift3` onto master
- tag a new 1.0.4 release/podspec in master

That'll make sure people on swift 2 have the newest when using that branch.

The readme has been updated for swift 3. I might have to revisit the code samples (not the example projects, just in the readme) to make sure they're right.

**Comment by bre7** [comment]
👍

**Comment by ogezue** [comment]
What is currently needed to run a swift 3.0 migrated project with PermissionScope?

**Comment by nickoneill** [comment]
Use the `swift3` branch with cocoapods or carthage @ogezue

**Comment by bclubb** [comment]
I'm trying 

`pod 'PromiseKit', :git => 'https://github.com/nickoneill/PermissionScope.git', :branch => 'swift3'`

but getting `[!] Unable to find a specification for 'PromiseKit'.`

Is there something obvious that I'm doing wrong with the podfile?  Great project.

**Comment by nickoneill** [comment]
@bclubb The pod name is `PermissionScope`, not `PromiseKit`

**Comment by bclubb** [comment]
Sorry, going through my podfile and updating for swift3.  Great project

**Comment by nickoneill** [comment]
Master is now swift 3 with version 1.1... I'm still fighting cocoapods to get the update pushed there

**Comment by nickoneill** [comment]
Should be done now, at version 1.1.1 after much fighting.
