### ISSUE TITLE
When the master branch will be turn into a tagged version?

### ISSUE THREAD

**Issue by RafaelPlantard** [nickoneill/PermissionScope#179]
When I use cocoa pods in my personal pod the version tagged 1.0.2 is older than the master version.
And I need the fix of Selector to #selector that is in master branch.
Can you help me?

**Comment by bre7** [comment]
Use master in your Podfile until a new version is released :)

``` ruby
  pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git'
```

**Comment by RafaelPlantard** [comment]
In a PodSpec file that is unavailable...
I need put this dependence inside my personal cocoa pod.

**Comment by bre7** [comment]
Sub-modules until a new version is released ?

**Comment by RafaelPlantard** [comment]
Okay, I will use sub-modules, but do you have some date to new release?

**Comment by bre7** [comment]
Not sure. I think the new version will be pushed using Swift 3
