### ISSUE TITLE
Add public method for getting back all permission status

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#18]
Or requesting specific statuses.

Also, a Parse extension to plop these all into a permission class unique by user id + installation id

**Comment by bre7** [comment]
> all permission status

configuredPermissions ? Make the computed variables public then ?

> Also, a Parse extension to plop these all into a permission class unique by user id + installation id

Permission class ?

**Comment by nickoneill** [comment]
Did this in 13710e8

As for the Parse stuff... it probably just belongs in my main project for now.
