### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by pjebs** [nickoneill/PermissionScope#183]
Is there anything in the library that prevents iOS 7 support.
I looked through code quickly but I don't seem to see anything incompatible with iOS 7.

**Comment by pjebs** [comment]
Unfortunately I don't have iOS 7 device to test it out on.

**Comment by vijaysanghavi** [comment]
You can try the same on iOS 7 simulator by downloading it in xcode.

_-------------------_
_Best Regards,_
_Vijay Sanghavi_
_iOS Developer_
_Contact: +91-9987597775_
_"Logic will get you from A to B. Imagination will take you everywhere."
http://vijaysanghavi.branded.me_

**Comment by nickoneill** [comment]
Sorry, not enough time or interest in supporting iOS 7 at this point.
