### ISSUE TITLE
Mobile data permission should be added

### ISSUE THREAD

**Issue by vijaysanghavi** [nickoneill/PermissionScope#184]
This is a Enhancement request in existing repo. I am checking for internet connectivity through Reachability classes which works very fine for me. 

Now what I am trying to achieve is to show Mobile Data permission in permission scope dialog. If user has denied the Mobile Data from system settings than the application will ask forcibly for Mobile Data permission through permission scope dialog else they can't use application further.

**Comment by nickoneill** [comment]
Sorry @vijaysanghavi, apps cannot control or see the Mobile Data setting on a per-app or device level.
