### ISSUE TITLE
Swift 3 Errors

### ISSUE THREAD

**Issue by ingeniousgenius** [nickoneill/PermissionScope#189]
I updated the code with the current Swift3 code, but I still get the errors in `PermissionScope.swift` on line 283 and a bunch of others. It directs me to here `frame.offsetInPlace`

The full error is this

> Value of type 'CGRect' has no member 'offsetInPlace'

 And I tried searching the documentation to see if its deprecated but I can find it anywhere. 

Also, I get another error on line `112` and other lines. The code causing the error is `let result = results
                .first { $0.status != .authorized }
                .isNil
            completion(result)
`

> Ambiguous use of `first(where:)`

**Comment by ingeniousgenius** [comment]
This can be closed. I didn't realize the other files were changed too.

**Comment by deivitaka** [comment]
@jesster2k10 how did you solve this?

**Comment by ingeniousgenius** [comment]
I'm not sure anymore. I can try look for the code I used if you wish?

**Comment by deivitaka** [comment]
Never mind, thanks. It was renamed to _offsetBy_ I think, however I got past that.
