### ISSUE TITLE
Add permission for Activity Monitoring

### ISSUE THREAD

**Issue by ramikay** [nickoneill/PermissionScope#19]
For an app to access CMMotionActivityManager

**Comment by nickoneill** [comment]
Good catch!

**Comment by bre7** [comment]
There's no way to check for the permission status, only when requesting you are able to verify the error.code :cry: 

Also, I think we need to assume the following ([CMError codes](https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMMotionManager_Class/#//apple_ref/c/tdef/CMError)):
- Device supports motion activity (CMErrorMotionActivityNotAvailable will never occur)
- App has necessary entitlements (CMErrorMotionActivityNotEntitled will never occur)

**Comment by fotiDim** [comment]
@nickoneill @bre7 
I have motion activity working all right. In fact I have submitted an app to the App Store with it. There are just a two bugs I want to look into. However as the project I was working on was in ObjC I used this pull request's code as a starter: https://github.com/nickoneill/PermissionScope/pull/49 . So I suggest that I hold on until you merge this one.

**Comment by nickoneill** [comment]
Working this in #53

**Comment by nickoneill** [comment]
Fixed
