### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by pjebs** [nickoneill/PermissionScope#195]
I submitted an app which got rejected today due to:

```

Design - 4.5.4


Also, we noticed that your app requires Push Notifications in order to function.

Next Steps

Push Notifications must be optional.

```

Is this a new policy? Has anyone else had this before?

**Comment by nickoneill** [comment]
I haven't heard of this before but it's not a surprising rule for the app store. By default PermissionScope should present your permissions as optional, i.e. if you cancel the dialog via the X button or tapping on the background, it should allow the user to continue.

Are you overriding this behavior to force the notifications permission?

**Comment by pjebs** [comment]
I force the user to accept push notifications in order to proceed. In the callback, I was using `finished`. I guess I can't use `finished` anymore.

**Comment by nickoneill** [comment]
👍
