### ISSUE TITLE
XCode 8 and Swift 3 

### ISSUE THREAD

**Issue by majidsaleem105** [nickoneill/PermissionScope#198]
I took xcode updates and downloaded latest swift 3.0 SDKs last week. I have been using few other libraries like SwiftyDB, Alamofire and PermissionScope in my project. I have taken updates using 'POD Update', everything is working except "PermissionScope". It is giving following errors:

Warning:  Target 'PermissionScope' of project 'Pods' was rejected as an implicit dependency for 'PermissionScope.framework' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'

Error:
ld: framework not found PermissionScope
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have tried following solutions but got no luck:
Solution# 1:
- Removed Podfile.lock file and Pod folder
- Run "Pod update" command again. It downloaded latest libraries for all of them. I got PermissionScope 1.0.3 as well.
- Cleaned Project and tried to build again

Solution# 2:
- Downloaded "PermissionScope" zip from Swift3 branch and tried to integrate it with my project.

Solution# 3:
- Set "Build Active Architecture Only" to "No" for all used libraries including "PermissionScope" but got no luck.

![new error](https://cloud.githubusercontent.com/assets/1611600/18630110/bd8ea934-7e83-11e6-80f6-66eb784e85bb.png)

**Comment by nickoneill** [comment]
@majidsaleem105 Have you tried specifying the swift3 branch for PermissionScope in your Podfile?I think your `framework not found` issue is related to not setting up the downloaded zip correctly, I would stick with cocoapods if you have that setup and (previously) working.

**Comment by majidsaleem105** [comment]
@nickoneill Yes, I specified swift3 branch for PermissionScope in my Podfile. I used cocoapods to set this up with my project and it was working perfectly fine for me. 

Here is my podfile contents:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'PTCK' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PTCK
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'PromiseKit'
  pod 'SwiftyDB'
  # pod 'PermissionScope'
  pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git', :branch => 'swift3'

end
```

I made 2 changes in it:
1. `platform :ios, '10.0'` [It was set as '9.0'.]
2. `# pod 'PermissionScope'` [commented and added below line.]
`pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git', :branch => 'swift3'`

Thanks for your help.

**Comment by majidsaleem105** [comment]
@nickoneill Any luck with this issue? Did you get a chance to take a look on this issue?

**Comment by nickoneill** [comment]
I'll have the swift3 stuff as a new release soon, I suggest you wait and try that again if the branch isn't working for you.

**Comment by nickoneill** [comment]
Please try again now, update your pod for master.

**Comment by majidsaleem105** [comment]
Thanks for the updates, I updated my pod file as you mentioned but unfortunately, it is still giving same error as I attached screenshot with my 1st message. Any suggestions?

**Comment by bre7** [comment]
``` bash
pod deintegrate
pod update
```

**Comment by majidsaleem105** [comment]
Thanks Nathan for your reply. I followed your instructions but no luck. I don't understand the following warning with error. Am I missing something?

Warning: Target 'PermissionScope' of project 'Pods' was rejected as an implicit dependency for 'PermissionScope.framework' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'

Error:
ld: framework not found PermissionScope
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nickoneill** [comment]
This strikes me as an integration issue @majidsaleem105, I suspect you may have messed with your project settings when switching to the download-zip-and-install. Is there a way you can revert back before you started messing with permissionscope, test updating to 1.1.1 (swift 3) and report back?
