### ISSUE TITLE
Callback After User accepts all permissions

### ISSUE THREAD

**Issue by AdventuresOfMar** [nickoneill/PermissionScope#204]
Hello All,

This is actually just a question. Is there currently a callback once a user accepts permissions. Essentially what I'm trying to do is wait until a user accepts all permissions or cancels permission scope to segue into the next view controller. Thanks for your time.

**Comment by bre7** [comment]
The only callback available is triggered each time PS detects a status change.

**Comment by nickoneill** [comment]
@AdventuresOfMar you can loop through the status for all requested permissions when each permission is triggered, as @bre7 suggests. I highly recommend you don't block entrance into a different view controller unless your app is fundamentally incompatible without permissions (such as camera + microphone for a video streaming app). In addition, Apple likes to reject apps that force the user to accept permissions such as notifications.

**Comment by bre7** [comment]
~~IIRC there was a callback named `allAccepted` or something like that~~

Check `allAuthorized(_:)`: [link](https://github.com/nickoneill/PermissionScope/blob/master/PermissionScope/PermissionScope.swift#L110)
