### ISSUE TITLE
Custom Permission creation 

### ISSUE THREAD

**Issue by Zornikachu** [nickoneill/PermissionScope#206]
Hi everyone, 

I would like to use PermissionScope to add custom Permissions to enable or disable certain features in my app.  I tried to implement it so far it's looking good, but before any release I would like to know if it's something the MIT license enables.

**Comment by nickoneill** [comment]
Hi @Zornikachu, you should feel free to copy or extend the code in any way you see fit, there are no restrictions.

**Comment by bre7** [comment]
Here are the cliff notes on MIT: https://tldrlegal.com/license/mit-license

![mit](https://cloud.githubusercontent.com/assets/3183848/19736497/e6adf2ba-9b85-11e6-9c4a-025d53242196.png)
