### ISSUE TITLE
Deprecation warning ios10

### ISSUE THREAD

**Issue by ogezue** [nickoneill/PermissionScope#208]
PermissionScope/PermissionScope.framework/Headers/PermissionScope-Swift.h:205:45: 'UIUserNotificationCategory' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationCategory

**Comment by bre7** [comment]
Related to #190. Fixed in #191

**Comment by ogezue** [comment]
So it is fixed but the cocoapods is not up to date?

**Comment by bre7** [comment]
#191 hasn't been merged yet, hence its "open" status.
