### ISSUE TITLE
Change the height of the dialog based on how many items are being requested

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#22]
This way we can use the dialog as a small notification permission request too

**Comment by bre7** [comment]
AutoLayout ? :D

**Comment by nickoneill** [comment]
hahhahahhaaahaaa

**Comment by nickoneill** [comment]
In all seriousness, I think it's less crazy to just manually adjust it to one of those three options.

**Comment by bre7** [comment]
Yeah.

let height = baseHeight + (labelHeight \* count(configuredPermissions))

**Comment by nickoneill** [comment]
Added this in 758fda7ce002de2131c982e8df9d1df5c6f73dee
