### ISSUE TITLE
Issue with NotificationRequest

### ISSUE THREAD

**Issue by LinusGeffarth** [nickoneill/PermissionScope#27]
Hey,
First off: this is really cool and I am happy that I came across this, so **thank you**!!

Now, I am having an issue with requesting notifications. When I use this code:

`let pscope = PermissionScope()
        pscope.addPermission(PermissionConfig(type: .Notifications, demands: .Optional, message: "We use this to send you\r\nspam and love notes", notificationCategories: Set([somePreviouslyConfiguredCategory])))
        pscope.show()
`

...what do I have to insert for `somePreviouslyConfiguredCategory`? It says it is an extra argument so I removed everything until the last quote. When I do so it runs and works until pressing the _Enable Notifications_.

What can I do?
Thanks again and keep up the great work :)

**Comment by bre7** [comment]
Linus, the _notificationCategories_ parameter is optional, intended to be used when you want to use interactive/actionable notifications ([Apple Docs](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW35)).

If you are going to use notification actions:

``` swift
var acceptAction = UIMutableUserNotificationAction()
// Configure the user notification action
var actionCategory = UIMutableUserNotificationCategory()
actionCategory.identifier = "some_id"
actionCategory.setActions([acceptAction], forContext: UIUserNotificationActionContext.Default)

let pscope = PermissionScope()
pscope.addPermission(
    PermissionConfig(type: .Notifications,
        demands: .Optional,
        message: "We use this to send you\r\nspam and love notes",
        notificationCategories: Set([actionCategory])
    )
)
pscope.show()
```

else use:

``` swift
let pscope = PermissionScope()
pscope.addPermission(
    PermissionConfig(type: .Notifications,
        demands: .Optional,
        message: "We use this to send you\r\nspam and love notes",
    )
)
pscope.show()
```

Another example (screenshots included): [Notifications in iOS 8 Part 2](http://thecodeninja.tumblr.com/post/90742435155/notifications-in-ios-8-part-2-using-swift-what)

**Comment by LinusGeffarth** [comment]
Hey,
Thanks for the quick response!

Look, as shown in the screenshot, it complains either way:

![screen shot 2015-06-03 at 22 52 54](https://cloud.githubusercontent.com/assets/9455439/7977799/60348ce6-0a43-11e5-8329-bcdaca965a11.png)

Weird thing is that here it works (except crashing):

![screen shot 2015-06-03 at 22 55 26](https://cloud.githubusercontent.com/assets/9455439/7977847/a931f4d8-0a43-11e5-8937-716cf7c1e244.png)

Thanks

**Comment by bre7** [comment]
I made a mistake in the second example :( There's an extra coma after the message

**Comment by LinusGeffarth** [comment]
Yeah I could think of that already, no problem. Thats why my code in the second image works ;)
But still, the app crashes when I use that code & then press the button or anywhere else…

**Comment by bre7** [comment]
What's the crash error ?

**Comment by LinusGeffarth** [comment]
There is none, thats the problem. It only says "(lldb)":

![screen shot 2015-06-03 at 23 20 23](https://cloud.githubusercontent.com/assets/9455439/7978160/28186d6a-0a47-11e5-962c-58c138fe4331.png)

**Comment by bre7** [comment]
Is the var _pscope_ stored in the view controller ? Or do you create it inside a function ? Try the first option.

**Comment by LinusGeffarth** [comment]
Super cool! Thank you so much :)
(creating it as global variable was the solution)

**Comment by nickoneill** [comment]
Hey @bre7, I realized when doing the example app that it breaks if you create and use a pscope inline (cleaned up before the delegate gets to call back I'm guessing) rather than holding it in global or class scope.

Other than changing the example to reflect this pattern (which I'll be doing soon), do you have any other ideas for ways we can mitigate this issue?

**Comment by bre7** [comment]
Nope, I'll have a look tomorrow or monday though =S I noticed the same when I first downloaded the project, if you enable zombies it displays the cause.

**Comment by nickoneill** [comment]
Yeah, I noted that zombies are probably an issue in #25. Better documentation it is!
