### ISSUE TITLE
Resizing depending on # of requests

### ISSUE THREAD

**Issue by LinusGeffarth** [nickoneill/PermissionScope#28]
How about resizing the view containing the requests depending on the # of requests?
So lets say I need 3 permissions then the view will have its complete size while for 1 it will automatically be smaller? (in sense of shorter on the y-axis)

Thanks :)

**Comment by nickoneill** [comment]
Hi Linus, this should already occur based on fixes from #22. Are you still seeing a large dialog for just one permission?

How are you pulling PermissionScope into your project? I haven't updated the podspec in a bit so you might not be getting all the newest changes if you're using cocoapods. Grab it manually for all the newest stuff for now.

**Comment by bre7** [comment]
Or use:

```
pod 'PermissionScope',  :head
```

**Comment by nickoneill** [comment]
Or that :+1:

**Comment by LinusGeffarth** [comment]
Oh ok, I used CocoaPods for PermissionScope 0.4 but I changed so many things :(
I can't seem to find where you resize the `contentView`...can you tell me?

**Comment by nickoneill** [comment]
https://github.com/nickoneill/PermissionScope/commit/758fda7ce002de2131c982e8df9d1df5c6f73dee

**Comment by LinusGeffarth** [comment]
Cool, thanks :)
