### ISSUE TITLE
Bug after cancelling Requests

### ISSUE THREAD

**Issue by LinusGeffarth** [nickoneill/PermissionScope#29]
I open the request view with a button. When I cancel the request by using the default feature by tapping the background and then press the button again it looks the following:

![screen shot 2015-06-03 at 23 54 03](https://cloud.githubusercontent.com/assets/9455439/7978589/dba085bc-0a4b-11e5-857d-d227818f4250.png)

**Comment by bre7** [comment]
Similar to #14, I'll have a look later if nick hasn't by then.

**Comment by LinusGeffarth** [comment]
Cool, thanks :)
And sorry, I did not see that one...

**Comment by nickoneill** [comment]
This was resolved in #14. I'll make note of how to pull the newest stuff with cocoapods in the readme.

**Comment by LinusGeffarth** [comment]
Alright, thanks for the support :)
