### ISSUE TITLE
Swift2 compatibility

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#37]
@nickoneill, new branch or wait til a stable release ?

**Comment by nickoneill** [comment]
Feel free to make a branch if you'd like to hack on it now. I'm going to wait for b2 before I start converting any of my projects.

**Comment by bre7** [comment]
:P

**Comment by nickoneill** [comment]
SOON

**Comment by bre7** [comment]
Swift2 fixes added. If it weren't for ObjC compatibility, PermissionType enum would only be one line :/

**Comment by nickoneill** [comment]
This is in the swift2 branch for now.
