### ISSUE TITLE
Allow users to cancel by tapping the background overlay

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#4]

**Comment by nickoneill** [comment]
In fact the only way to cancel!

**Comment by otymartin** [comment]
@nickoneill how can I disable this? For some use case like say snapchat, permissions MUST be granted for the app to be functional. I can hide the close button but how can I disable `cancel` from background overlay?

**Comment by nickoneill** [comment]
@otymartin You can't remove the background close functionality at the moment. I would gate the permissions-required part of your app with a pscope dialog, before pushing your view controller that required permissions.
