### ISSUE TITLE
Add index to readme

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#41]

**Comment by nickoneill** [comment]
Yeah, I need to restructure the whole thing too. And do some more work on documentation.

**Comment by bre7** [comment]
Single page readme or wiki ?

**Comment by nickoneill** [comment]
Short single-pager with animated GIF (working on this!) plus either wiki or really good code documentation site... the cocoapods one looks nice: http://cocoadocs.org/docsets/PermissionScope/0.6/Classes/PermissionScope.html

**Comment by bre7** [comment]
https://appetize.io/upload ? Cocoacontrols started using it and it's pretty great.

**Comment by bre7** [comment]
Added (wip/health-cloud-kit branch)
