### ISSUE TITLE
Remove optional/required demands

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#51]
This was the wrong way to go, users can manage how the dialog behaves in the callback. See issue #50

**Comment by bre7** [comment]
They are all required atm ([PermissionScope.swift#L848](https://github.com/bre7/PermissionScope/blob/wip/health-cloud-kit/PermissionScope/PermissionScope.swift#L848)), since `requiredAuthorized()` and `allAuthorized()` return the same value.

**Comment by nickoneill** [comment]
Removed the demands in swift2 a few days ago.
