### ISSUE TITLE
Allow customization of permissions button names

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#6]

**Comment by nickoneill** [comment]
This seems to be a constant source of forks so might be wise to do this for v1

**Comment by bre7** [comment]
The text ? It's partially implemented, though not in code but rather using localization. Check https://github.com/nickoneill/PermissionScope/pull/12#issuecomment-96428580.

**Comment by nickoneill** [comment]
Oh, right. I'll make note of this in the readme.

**Comment by nickoneill** [comment]
Done
