### ISSUE TITLE
Add framework archive to release

### ISSUE THREAD

**Issue by ky1ejs** [nickoneill/PermissionScope#62]
Incase you didn't know (I only found out today :joy:), all you have to do is:

``` shell
$ carthage build --no-skip-current

$ carthage archive PermissionScope
```

Then just upload the .zip in the project root.

This will save a bunch of time on CI server and the like.

**Comment by nickoneill** [comment]
Thanks Kyle! Does this work the same as tags for the source? i.e. I have to make a new release for the archive to be picked up by the tools?

**Comment by ky1ejs** [comment]
No problem! No, you can add it to an existing release and Carthage will pick it up :tada:

**Comment by nickoneill** [comment]
Knee-deep in swift2 refactoring... we'll definitely get this in for that release.

**Comment by ky1ejs** [comment]
No worries! If you need help, let me know. I love this project and I'm pretty certain we're going to be shipped in our application.

If you need extra owners for some stuff like this, holler at me.

**Comment by nickoneill** [comment]
I'll gladly take a PR to put this in master/swift1.2 if you need it ASAP. I'm not sure how inconvenienced not having this makes people.

**Comment by ky1ejs** [comment]
I don't think I can PR adding files to tags, otherwise I would.

No worries :)

**Comment by nickoneill** [comment]
Just added this in 1.0.1. Give it a shot and let me know if it works for you @kylejm

**Comment by ky1ejs** [comment]
@nickoneill I just checked out 1.0.1 but it looks like there's not a PermissionScope.framework.zip attached

![screen shot 2015-09-22 at 12 08 27](https://cloud.githubusercontent.com/assets/3501212/10016976/c10c9b5e-6122-11e5-95d6-50646908fb65.png)

**Comment by nickoneill** [comment]
OK, I attached a binary to that tag: https://github.com/nickoneill/PermissionScope/releases/tag/1.0.1

I believe it's independent of the version checked in to the project root. Can you link me to the docs that describe how Carthage wants the file for CI?

**Comment by ky1ejs** [comment]
Ahhhh, I see. I didn't realise you'd put it in the project root :smile: 

I'm not sure if this works, but even if it did, it's not a good idea, since the `.framework.zip` is an artefact and therefore shouldn't be tracked by Git. It's also quite nice to have each `.framework.zip` attached to it's corresponding release tag. This allows you to quickly download and integrate with any version of the framework (via Carthage or not).

Carthage docs say:

> Carthage can automatically use prebuilt frameworks, instead of building from scratch, if they are attached to a **GitHub Release** on your project’s repository.

It's in their [README](https://github.com/Carthage/Carthage) under **Archive prebuilt frameworks into one zip file** towards the bottom.

**Comment by nickoneill** [comment]
Yeah, totally agree. Let me know if the current setup works and I'll do it for subsequent releases.

**Comment by ky1ejs** [comment]
Worked great :tada:

**Comment by nickoneill** [comment]
:+1:
