### ISSUE TITLE
Extra init parameters alternatives for PermissionConfig

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#71]
We need a better approach instead of adding extra parameters to PermissionConfig's initializer.
If associated values are used in enums, allValues can't be used since we don't have the parameters for them.

Associated values, extra init parameters or a better solution (some sort of plugin system?)

**Comment by nickoneill** [comment]
Can you clarify why you think the current system is bad? I'm still rather fond of it.

**Comment by bre7** [comment]
Not bad, but quite messy if we add Accounts and HealthKit since they require 3 extra parameters in total (2 new Sets for HK and a Dictionary for Facebook) :S
Which also would entail adding extra asserts to ensure those new parameters are !Optional for those specific permissions.

Something like:

``` swift
public init(type: PermissionType, demands: PermissionDemands, message: String, 
    notificationCategories: Set<UIUserNotificationCategory>? = .None,
    facebookPermissions: [NSObject:AnyObject]?, healthTypesToShare: Set<HKSampleType>?,
    healthTypesToRead: Set<HKObjectType>?) {

        if type != .Notifications && notificationCategories != .None {
            assertionFailure("notificationCategories only apply to the .Notifications permission")
        }

        self.type = type
        self.demands = demands
        self.message = message
        self.notificationCategories = notificationCategories
}
```

**Comment by nickoneill** [comment]
Oh I see what you're saying now.

Instead, we can simply provide a permissionconfig protocol and break each service into a new file / struct / class. That way each one can provide its own initializer (`HealthPermissionConfig(...)`) and we can keep complex logic like the async stuff or the notification tracker in those separate files.

**Comment by bre7** [comment]
Indeed, cleaner code. I'll try this new solution with HealthKit this week.

Are you going to release 1.0 as-is or wait for these new changes ?

**Comment by nickoneill** [comment]
:+1: Let me know if you want to bounce any ideas off me, I'm interested in figuring out all the nitty gritty details too.

**Comment by bre7** [comment]
I'm still thinking about the async requests, specially if using GCD (I'm still getting the hang of it) or [Async](https://github.com/duemunk/Async) which is a pretty nice wrapper.

Would you mind adding third-party dependencies ?

**Comment by nickoneill** [comment]
If you're more comfortable with Async, build it using that. We can always refactor to GCD which I'm pretty comfortable with.

**Comment by bre7** [comment]
> Instead, we can simply provide a permissionconfig protocol and break each service into a new file / struct / class.

No structs because of ObjC compatibility :/

UPDATE: PermissionConfig is a Protocol for now
