### ISSUE TITLE
Add an option to reinitialize PermissionScope

### ISSUE THREAD

**Issue by evermeer** [nickoneill/PermissionScope#73]
As discussed in issue #58: 

When PermissionScope is shown and an event was triggered that should cause a reevaluation of the permissions then currently the following workaround is required:
First execute the hide function, then wait for a second and call the show function.

I used this workaround in in EVCloudKitDao after the NSUbiquityIdentityDidChangeNotification was called the moment the PermissionScope screen was still open.  

It would be nice if there was a method in PermissionScope to reinitialize everything.

**Comment by nickoneill** [comment]
I'm not 100% on the use case here (I also haven't been dealing with CloudKit permissions much) but it sounds like our "pending" status support as mentioned in #58 will take care of this. Is that correct @evermeer?
