### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#78]
_In progress_

**Comment by bre7** [comment]
@felix-dumit @Navideck-fotis could either of you add doc for the CMMotion and Bluetooth related functions and variables ? Use [VVDocumenter](https://github.com/onevcat/VVDocumenter-Xcode) if you don't already have it.

**Comment by felix-dumit** [comment]
Didn't know VVDocumenter worked with swift :+1: 
@bre7 I checked and there are already docs for bluetooth, did you just want me to double check them?

**Comment by bre7** [comment]
Yeah, since I wasn't 100% sure about the workflow (CMMotion especially since I didn't implement any of it)

Btw, use VVDoc's [swift-2.0 branch](https://github.com/onevcat/VVDocumenter-Xcode/tree/swift-2.0) but beware that Alcatraz updates it with the master branch every time you open Xcode

**Comment by nickoneill** [comment]
Are we missing anything here? Everything looks pretty well documented to me.

**Comment by bre7** [comment]
It's ok for now.

Missing:
- [x] `showingNotificationPermission()` [L539](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L539)
- [x] `notificationTimer` [L550](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L550)
- [x] `finishedShowingNotificationPermission()` [L553](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L553)
- [x] `triggerBluetoothStatusUpdate()` [L853](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L853)
- [x] `detectAndCallback()` [L1267](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L1267)
- [x] `getResultsForConfig(:)` [L1296](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L1296)
- ~~`finish()` [L1139](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L1139)~~ function removed
- [x] `appForegroundedAfterSettings()` [L1224](https://github.com/nickoneill/PermissionScope/blob/swift2/PermissionScope/PermissionScope.swift#L1224)

They all have `// TODO: Add doc` comments

Update: @nickoneill nice, they are all done now I think.
