### ISSUE TITLE
Add spinner to button on async status calls

### ISSUE THREAD

**Issue by evermeer** [nickoneill/PermissionScope#84]
When calling the statusCloudKit method it could take a couple of seconds before the callback function is called. It would be nice if the button had an unknown state that maybe would include a spinner inside the button. Currently you will see an 'allow cloudkit' button which will suddenly change to 'allowed cloudkit' and changes color.

**Comment by bre7** [comment]
Nice catch ;D I'll have a look this week If I can but after #79

**Comment by nickoneill** [comment]
This is definitely related to how we plan on dealing with cloudkit as a whole (#58). I agree that something should indicate uncertainty when we display the dialog, this is the right direction to go for that.

I added some thoughts there on how we should deal with this technically, this issue may be wrapped into that one if the solutions are converging as they seem to be.
