### ISSUE TITLE
Check NSLocationWhenInUseUsageDescription when asking for location permission

### ISSUE THREAD

**Issue by evermeer** [nickoneill/PermissionScope#87]
When doing an .addPermission for LocationWhileInUsePermission or LocationAlwaysPermission  the key NSLocationAlwaysUsageDescription or NSLocationWhenInUseUsageDescription has to be setup in the info.plist.

You can test it with code like this:

``` swift
let hasAlwaysKey = !NSBundle.mainBundle()
    .objectForInfoDictionaryKey("NSLocationAlwaysUsageDescription").isNil
let hasWhenInUseKey = !NSBundle.mainBundle()
    .objectForInfoDictionaryKey("NSLocationWhenInUseUsageDescription").isNil
```

And if it's false then execute something like:

``` swift
assert(hasAlwaysKey, "To use location services in iOS 8+, your Info.plist must provide a value for either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription.")
```

**Comment by nickoneill** [comment]
Nice catch, this is really helpful for users. I can only wonder why Apple doesn't do this themselves.

**Comment by bre7** [comment]
~~@evermeer test the new PR if you can and I'll merge it.~~

Done.
