### ISSUE TITLE
Swapping swift2 ~ master ~ swift12

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#95]
FYI, I plan on swapping these out in the next day or two. The swift2 branch will become master at version 1.0 (as to not break anyone autoupdating with cocoapods) and the existing master branch will live on a new swift12 branch.

@bre7 @felix-dumit @evermeer @winzig Will that work with how everyone is currently using PermissionScope? I want to get a quick OK/Not OK from people to make sure I'm not forgetting a use case where people will be autoupdated to swift2 when they don't want to be.

**Comment by bre7** [comment]
Yeah. That's how other libs usually update to a new swift version also.

P.S: Nice banner :wink:

**Comment by evermeer** [comment]
Yes, that will work fine. I did the same with my repositories.
You don't even have to make a swift12. branch unless you are planning to make updates to it.
Otherwise people can just use the version number in order to get the swift 1.2 compatible version

**Comment by bre7** [comment]
> You don't even have to make a swift12. branch unless you are planning to make updates to it.

Makes it easier for others to fork though.

**Comment by winzig** [comment]
Works for me, thanks

**Comment by felix-dumit** [comment]
Ok!

**Comment by nickoneill** [comment]
All set here.
