### ISSUE TITLE
Optional import of Healtkit

### ISSUE THREAD

**Issue by felix-dumit** [nickoneill/PermissionScope#97]
I submitted my app to the appstore but it was rejected with the following:

"27.6 - Apps using the HealthKit framework must indicate integration with the Health app in their marketing text and must clearly identify the HealthKit functionality in the app's user interface"

I'm not using Healthkit anywhere in my code so it must be due to PermissionScope. 
So we need a way to make HealthKit optional, maybe in a subspec.

**Comment by bre7** [comment]
Ahh :( yeah, sub-specs seem to be the way to go. What about Carthage ? New xcodeproj per subspec ?

**Comment by nickoneill** [comment]
I was just approved for beta testing with the newest pscope code - afaik they want you to adhere to the guidelines for testflight as well as releases and this feels like something they would detect automatically. Are you sure it's not something else? An errant healthkit entitlement?

**Comment by bre7** [comment]
HK capability is off right ?

**Comment by felix-dumit** [comment]
The app was approved for test flight beta, but rejected for the store.
I have not enabled health kit in capabilities.

**Comment by nickoneill** [comment]
Ah, OK. Thanks for the tip. I'll work on this today.

**Comment by gloparco** [comment]
In general this would be a good thing anyway - if your app doesn't use HealthKit, why should you be forced to include it?  Makes sense, no?

**Comment by bre7** [comment]
Yeah ;)

Remove HK for now and push 0.9.1 ? (Remove the GCD code using groups, there's no need for that since we are going to add the Pending status)

**Comment by nickoneill** [comment]
The healthkit stuff is so unpolished right now, I feel OK with removing it from a 1.0.1 release @bre7.

@gloparco If you don't ask for them, permissionscope doesn't load or call any HealthKit APIs. It's possible that the import statement was linking the HealthKit framework through. Definitely a good reason to split stuff into files/subspecs.

**Comment by bre7** [comment]
Should be ok now

**Comment by nickoneill** [comment]
Please give 1.0.1 a shot with this. I've removed all mentions of HealthKit and we'll work it back in via subspec soon.

**Comment by felix-dumit** [comment]
I resubmitted. Will let you know the outcome

**Comment by felix-dumit** [comment]
Update here: The app was still rejected and I'm appealing (been a month already :disappointed:) but it had nothing to do with HealthKit so **we're good**.

**Comment by bre7** [comment]
Reopen the issue if the rejection turns out to be due to PScope
